from dataclasses import dataclass
from enum import Enum


class CoverageType(Enum):
    """
    An enumeration representing different types of code coverage reports.

    Attributes:
        LCOV: Represents the LCOV coverage report format.
        COBERTURA: Represents the Cobertura coverage report format.
        JACOCO: Represents the JaCoCo coverage report format.
    """
    LCOV = "lcov"
    COBERTURA = "cobertura"
    JACOCO = "jacoco"


@dataclass
class CoverAgentConfig:
    """
    A data class representing the configuration for the CoverAgent.

    Attributes:
        source_file_path (str): Path to the source file.
        test_file_path (str): Path to the test file.
        project_root (str): Path to the root of the project.
        test_file_output_path (str): Path to the output test file.
        code_coverage_report_path (str): Path to the code coverage report file.
        test_command (str): The command to run tests and generate coverage report.
        test_command_dir (str): The directory to run the test command in.
        included_files (str): List of files to include in the coverage.
                              For example, "--included-files library1.c library2.c.".
        coverage_type (CoverageType): Type of coverage report.
        report_filepath (str): Path to the output report file.
        desired_coverage (int): The desired coverage percentage
        max_iterations (int): The maximum number of iterations.
        max_run_time (int): Maximum time (in seconds) allowed for test execution.
        additional_instructions (str): Any additional instructions you wish to append at the end of the prompt.
        model (str): The API url to use for Ollama or Hugging Face.
        api_base (str): Base URL for the API.
        strict_coverage (bool): If set, Cover-Agent will return a non-zero exit code
                                if the desired code coverage is not achieved.
        run_tests_multiple_times (int): Number of times to run the tests generated by Cover Agent.
        log_db_path (str): Path to optional log database.
        branch (str): The branch to compare against when using --diff-coverage.
        use_report_coverage_feature_flag (bool): Setting this to True considers the coverage of all the files
                                                 in the coverage report.
        diff_coverage (bool): If set, Cover-Agent will only generate tests based on the diff between branches.
        run_each_test_separately (bool): Run each test separately.
    """
    source_file_path: str
    test_file_path: str
    project_root: str
    test_file_output_path: str
    code_coverage_report_path: str
    test_command: str
    test_command_dir: str
    included_files: list[str] | None
    coverage_type: CoverageType
    report_filepath: str
    desired_coverage: int
    max_iterations: int
    max_run_time: int
    additional_instructions: str
    model: str
    api_base: str
    strict_coverage: bool
    run_tests_multiple_times: int
    log_db_path: str
    branch: str
    use_report_coverage_feature_flag: bool
    diff_coverage: bool
    run_each_test_separately: bool
